export const employeesData = [
  {
    key: "VENX-1",
    name: "John Doe",
    productivity: 85,
    collaboration: 90,
    communication: 88,
  },
  {
    key: "VENX-2",
    name: "Jane Smith",
    productivity: 78,
    collaboration: 84,
    communication: 80,
  },
  {
    key: "VENX-3",
    name: "Alice Johnson",
    productivity: 92,
    collaboration: 88,
    communication: 95,
  },
  {
    key: "VENX-4",
    name: "Bob Brown",
    productivity: 70,
    collaboration: 75,
    communication: 72,
  },
  {
    key: "VENX-5",
    name: "Eve Davis",
    productivity: 88,
    collaboration: 92,
    communication: 90,
  },
  {
    key: "VENX-6",
    name: "Michael Lee",
    productivity: 80,
    collaboration: 85,
    communication: 83,
  },
  {
    key: "VENX-7",
    name: "Olivia Martinez",
    productivity: 89,
    collaboration: 93,
    communication: 87,
  },
  {
    key: "VENX-8",
    name: "David Clark",
    productivity: 75,
    collaboration: 79,
    communication: 78,
  },
  {
    key: "VENX-9",
    name: "Sophia Lewis",
    productivity: 90,
    collaboration: 88,
    communication: 91,
  },
  {
    key: "VENX-10",
    name: "Daniel Walker",
    productivity: 81,
    collaboration: 86,
    communication: 84,
  },
  {
    key: "VENX-11",
    name: "Mia Harris",
    productivity: 94,
    collaboration: 91,
    communication: 96,
  },
  {
    key: "VENX-12",
    name: "James Young",
    productivity: 79,
    collaboration: 82,
    communication: 80,
  },
  {
    key: "VENX-13",
    name: "Isabella King",
    productivity: 85,
    collaboration: 89,
    communication: 87,
  },
  {
    key: "VENX-14",
    name: "Matthew Scott",
    productivity: 78,
    collaboration: 76,
    communication: 79,
  },
  {
    key: "VENX-15",
    name: "Charlotte Green",
    productivity: 92,
    collaboration: 90,
    communication: 93,
  },
];
